### ISSUE TITLE
Dans le tutoriel pyTorch2 : quelques erreurs à l’exécution

### ISSUE THREAD

**Issue by memento** [nschaetti/NS.ai#1]
Bonjour,

Merci pour votre [tutoriel](https://youtu.be/RMcMl1EnBC8) !

En premier lieu, dès la première exécution, j'ai un 

```
jupyter@my-fastai-instance:~/project/NS.ai/pyTorch2$ python image_classification.py 
torch.Size([4, 1, 28, 28])
tensor([9, 0, 0, 3])
Traceback (most recent call last):
  File "image_classification.py", line 110, in <module>
    outputs = net(inputs)
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jupyter/project/NS.ai/pyTorch2/modules/Net.py", line 43, in forward
    x = x.view(-1, 16 * 4 * 4)
RuntimeError: shape '[-1, 256]' is invalid for input of size 64
jupyter@my-fastai-instance:~/project/NS.ai/pyTorch2$ nano image_classification.py 
jupyter@my-fastai-instance:~/project/NS.ai/pyTorch2$ python image_classification.py 
Traceback (most recent call last):
  File "image_classification.py", line 61, in <module>
    images, labels = dataiter.next()
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 615, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 615, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/opt/anaconda3/lib/python3.7/site-packages/torchvision/datasets/mnist.py", line 95, in __getitem__
    img = self.transform(img)
  File "/opt/anaconda3/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 60, in __call__
    img = t(img)
  File "/opt/anaconda3/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 163, in __call__
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/opt/anaconda3/lib/python3.7/site-packages/torchvision/transforms/functional.py", line 208, in normalize
    tensor.sub_(mean[:, None, None]).div_(std[:, None, None])
RuntimeError: output with shape [1, 28, 28] doesn't match the broadcast shape [3, 28, 28]

```
Grâce à ce [lien](https://stackoverflow.com/a/55124537) : 

Je corrige donc :

```python
transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
```

en : 

```python
transforms.Normalize((0.5,), (0.5,))
```

```python
jupyter@my-fastai-instance:~/project/NS.ai/pyTorch2$ python image_classification.py 
Traceback (most recent call last):
  File "image_classification.py", line 61, in <module>
    images, labels = dataiter.next()
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 615, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 615, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/opt/anaconda3/lib/python3.7/site-packages/torchvision/datasets/mnist.py", line 95, in __getitem__
    img = self.transform(img)
  File "/opt/anaconda3/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 60, in __call__
    img = t(img)
  File "/opt/anaconda3/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 163, in __call__
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/opt/anaconda3/lib/python3.7/site-packages/torchvision/transforms/functional.py", line 208, in normalize
    tensor.sub_(mean[:, None, None]).div_(std[:, None, None])
RuntimeError: output with shape [1, 28, 28] doesn't match the broadcast shape [3, 28, 28]
```
Avez-vous une idée ? :)

Ma version de python est : Python 3.7.1

<details open>
<summary>Un 'pip freeze' exhaustif me donne les versions des modules suivants, pour info : </summary>
<br>

- alabaster==0.7.12
- anaconda-client==1.7.2
- anaconda-navigator==1.9.6
- anaconda-project==0.8.2
- asn1crypto==0.24.0
- astroid==2.1.0
- astropy==3.1
- atomicwrites==1.2.1
- attrs==18.2.0
- Babel==2.6.0
- backcall==0.1.0
- backports.os==0.1.1
- backports.shutil-get-terminal-size==1.0.0
- bcolz==1.2.1
- beautifulsoup4==4.6.3
- bitarray==0.8.3
- bkcharts==0.2
- blaze==0.11.3
- bleach==3.0.2
- bokeh==1.0.2
- boto==2.49.0
- Bottleneck==1.2.1
- cachetools==3.1.0
- certifi==2019.3.9
- cffi==1.11.5
- chardet==3.0.4
- Click==7.0
- cloudpickle==0.6.1
- clyent==1.2.2
- colorama==0.4.1
- conda==4.6.8
- conda-build==3.17.6
- conda-verify==3.1.1
- contextlib2==0.5.5
- cryptography==2.4.2
- cycler==0.10.0
- cymem==2.0.2
- Cython==0.29.2
- cytoolz==0.9.0.1
- dask==1.0.0
- dataclasses==0.6
- datashape==0.5.4
- decorator==4.3.0
- defusedxml==0.5.0
- dill==0.2.8.2
- distributed==1.25.1
- docutils==0.14
- entrypoints==0.2.3
- enum34==1.1.6
- et-xmlfile==1.0.1
- fastai==1.0.50.post1
- fastcache==1.0.2
- fastprogress==0.1.20
- filelock==3.0.10
- Flask==1.0.2
- Flask-Cors==3.0.7
- future==0.17.1
- gevent==1.3.7
- gitdb2==2.0.5
- GitPython==2.1.11
- glob2==0.6
- gmpy2==2.0.8
- google-api-core==1.8.0
- google-api-python-client==1.7.8
- google-auth==1.6.3
- google-auth-httplib2==0.0.3
- google-cloud-bigquery==1.9.0
- google-cloud-core==0.29.1
- google-cloud-dataproc==0.3.1
- google-resumable-media==0.3.2
- googleapis-common-protos==1.5.8
- greenlet==0.4.15
- h5py==2.8.0
- heapdict==1.0.0
- html5lib==1.0.1
- httplib2==0.12.1
- idna==2.8
- imageio==2.4.1
- imagesize==1.1.0
- importlib-metadata==0.6
- ipykernel==5.1.0
- ipython==7.3.0
- ipython-genutils==0.2.0
- ipython-sql==0.3.9
- ipywidgets==7.4.2
- isort==4.3.4
- itsdangerous==1.1.0
- jdcal==1.4
- jedi==0.13.3
- jeepney==0.4
- Jinja2==2.10
- jsonschema==2.6.0
- jupyter==1.0.0
- jupyter-client==5.2.4
- jupyter-console==6.0.0
- jupyter-contrib-core==0.3.3
- jupyter-contrib-nbextensions==0.5.1
- jupyter-core==4.4.0
- jupyter-highlight-selected-word==0.2.0
- jupyter-http-over-ws==0.0.3
- jupyter-latex-envs==1.4.6
- jupyter-nbextensions-configurator==0.4.1
- jupyterlab==0.35.4
- jupyterlab-git==0.5.0
- jupyterlab-server==0.2.0
- keyring==17.0.0
- kiwisolver==1.0.1
- lazy-object-proxy==1.3.1
- libarchive-c==2.8
- lief==0.9.0
- llvmlite==0.26.0
- locket==0.2.0
- lxml==4.2.5
- MarkupSafe==1.1.0
- matplotlib==3.0.2
- mccabe==0.6.1
- mistune==0.8.4
- mkl-fft==1.0.6
- mkl-random==1.0.2
- more-itertools==4.3.0
- mpmath==1.1.0
- msgpack==0.5.6
- msgpack-numpy==0.4.3.2
- multipledispatch==0.6.0
- murmurhash==1.0.1
- navigator-updater==0.2.1
- nb-conda==2.2.1
- nb-conda-kernels==2.2.0
- nbconvert==5.4.1
- nbdime==1.0.4
- nbformat==4.4.0
- nbpresent==3.0.2
- networkx==2.2
- nltk==3.4
- nose==1.3.7
- notebook==5.7.4
- numba==0.41.0
- numexpr==2.6.8
- numpy==1.15.4
- numpydoc==0.8.0
- odo==0.5.1
- olefile==0.46
- opencv-python==4.0.0.21
- openpyxl==2.5.12
- packaging==18.0
- pandas==0.24.1
- pandocfilters==1.4.2
- parso==0.3.4
- partd==0.3.9
- path.py==11.5.0
- pathlib2==2.3.3
- patsy==0.5.1
- pep8==1.7.1
- pexpect==4.6.0
- pickleshare==0.7.5
- Pillow==5.3.0
- Pillow-SIMD==5.3.0.post0
- pkginfo==1.4.2
- plac==0.9.6
- pluggy==0.8.0
- ply==3.11
- preshed==2.0.1
- prettytable==0.7.2
- prometheus-client==0.5.0
- prompt-toolkit==2.0.9
- protobuf==3.6.1
- psutil==5.4.8
- ptyprocess==0.6.0
- py==1.7.0
- pyarrow==0.12.1
- pyasn1==0.4.5
- pyasn1-modules==0.2.4
- pycodestyle==2.4.0
- pycosat==0.6.3
- pycparser==2.19
- pycrypto==2.6.1
- pycurl==7.43.0.2
- pydot==1.4.1
- pyflakes==2.0.0
- Pygments==2.3.1
- pylint==2.2.2
- pyodbc==4.0.25
- pyOpenSSL==18.0.0
- pyparsing==2.3.0
- PySocks==1.6.8
- pytest==4.0.2
- pytest-arraydiff==0.3
- pytest-astropy==0.5.0
- pytest-doctestplus==0.2.0
- pytest-openfiles==0.3.1
- pytest-remotedata==0.3.1
- python-dateutil==2.8.0
- pytz==2018.7
- PyWavelets==1.0.1
- PyYAML==3.13
- pyzmq==17.1.2
- QtAwesome==0.5.3
- qtconsole==4.4.3
- QtPy==1.5.2
- regex==2018.1.10
- requests==2.21.0
- rope==0.11.0
- rsa==4.0
- ruamel-yaml==0.15.46
- scikit-image==0.14.1
- scikit-learn==0.20.1
- scipy==1.1.0
- seaborn==0.9.0
- SecretStorage==3.1.0
- Send2Trash==1.5.0
- simplegeneric==0.8.1
- singledispatch==3.4.0.3
- six==1.12.0
- smmap2==2.0.5
- snowballstemmer==1.2.1
- sortedcollections==1.0.1
- sortedcontainers==2.1.0
- spacy==2.0.18
- Sphinx==1.8.2
- sphinxcontrib-websupport==1.1.0
- spyder==3.3.2
- spyder-kernels==0.3.0
- SQLAlchemy==1.2.15
- sqlparse==0.2.4
- statsmodels==0.9.0
- sympy==1.3
- tables==3.4.4
- tblib==1.3.2
- terminado==0.8.1
- testpath==0.4.2
- thinc==6.12.1
- toolz==0.9.0
- torch==1.0.1.post2
- torchvision==0.2.2
- tornado==5.1.1
- tqdm==4.28.1
- traitlets==4.3.2
- typing==3.6.4
- ujson==1.35
- unicodecsv==0.14.1
- uritemplate==3.0.0
- urllib3==1.24.1
- wcwidth==0.1.7
- webencodings==0.5.1
- Werkzeug==0.14.1
- widgetsnbextension==3.4.2
- wrapt==1.10.11
- wurlitzer==1.0.2
- xlrd==1.2.0
- XlsxWriter==1.1.2
- xlwt==1.3.0
- zict==0.1.3

</details>

Note : Je teste votre code sur ma VM (google cloud mais même erreur sur une version modifiée du code pour Google Collab).
Je précise également que ma machine à un GPU et les drivers cuda fonctionnels.

Merci beaucoup d'avance !
Bonne nuit !

**Comment by pastrouveedespeudo** [comment]
au cas ou transforms.Normalize([0.5], [0.5]) peut etre que ca vous aidera si vous n'avez pas trouvé

**Comment by pastrouveedespeudo** [comment]
et moi j'ai RuntimeError: shape '[-1, 256]' is invalid for input of size 64

Avez vous une idée ? ^^

**Comment by memento** [comment]
J'ai essyé, ça me donne toujours une erreur : 

```
RuntimeError: shape '[-1, 256]' is invalid for input of size 64
```
